/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void say(String msg) {
        System.out.println(msg);
    }
}
