create-db:
	@mysql -uroot -proot -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS spring_jpa_demo_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"

drop-db:
	@mysql -uroot -proot -h 127.0.0.1 -e "DROP DATABASE spring_jpa_demo_dev"
