/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Library library = new Library();
        System.out.println("Library method returns: " + library.someLibraryMethod());

        Library.say("Hello from library");
    }
}
